#!/bin/bash
#
##
###                _       _
###  ___  ___ _ __(_)_ __ | |_     _ __   __ _ _ __ ___   ___
### / __|/ __| '__| | '_ \| __|   | '_ \ / _` | '_ ` _ \ / _ \
### \__ \ (__| |  | | |_) | |_    | | | | (_| | | | | | |  __/
### |___/\___|_|  |_| .__/ \__|___|_| |_|\__,_|_| |_| |_|\___|
###                 |_|      |_____|
###  _ _|_ _ ._    _  _
### (_\/|_(_)|_)\/(_|(/_
###   /      |  /  _|
###
### script_name
### description
###
### (c) 2020 cytopyge
###
##
#


# usage: <cli entry>
# guidelines


# initial definitions

## initialize hardcoded variables
script_name="script_name"
initial_release_year="2020"
developer="cytopyge"
source_dir="$HOME/_git/code/sources/functions"

# sourcing
for file in $source_dir; do
	source $file
done

## get functions
#get_sudo
#read_flags
#reply_functions
#splash_screen
#text_appearance
