#!/bin/bash
#
##
### source function
##
#


get_sudo() {

	## get sudo error status non interactive
	sudo -n printf "" > /dev/null 2>&1

	if [[ $? -ne 0 ]]; then

		set -e

		## reset cached credentials timestamp, always (re-)authenticate
		#sudo -k

		## validate; update cached credentials, authenticating only if necessary
		## is always necessary in this if statement
		echo
		printf "In order to obtain required privileges,\nplease enter ${YELLOW}"

		sudo -v

		printf "${NOC}"

		set +e

	fi

	#after get_sudo newline
	echo

}
