#!/bin/bash
#
##
### source function
###
### 2019 -2021 (c) cytopyge
##
#


get_sudo()
{

	## save screen content
	## ##tput smcup

	## get sudo error status non interactive
	sudo -n printf "" > /dev/null 2>&1

	if [[ $? -ne 0 ]]; then

		set -e

		## reset cached credentials timestamp, always (re-)authenticate
		#sudo -k

		## validate; update cached credentials, authenticating only if necessary
		## is always necessary in this if statement
		echo
		printf "obtaining sudo required privileges,\nplease enter ${YELLOW}"
		#printf "In order to obtain required privileges,\nplease enter ${YELLOW}"

		sudo -v

		printf "${NOC}"

		set +e


		#tput clear
		#tput rmcup
		## remove lines above cursor
		### restore cursor position
		#tput rc
		#tput cuu1
		#tput ed
		#tput cuu1
		### clear to end of screen
		#tput ed
		#after get_sudo newline

	fi

	# restore screen content
	## ##tput rmcup
	echo

}
