#!/bin/zsh
#
##
### source function
##
#


# reply functions definitions


reply_plain() {

	# entry is visible
	# string entry must be confirmed explicitly (by pushing enter)
	read reply

}


reply_plain_hidden() {

	# entry is not visible
	# string entry must be confirmed explicitly (by pushing enter)
    read -s reply

}


reply_single_hidden_timed() {

	# entry is not visible
    # first entered character goes directly to $reply
	# timer exits

	: '
	input_time=5
	tput sc

	while [ $input_time -ge 0 ]; do

		tput rc
		tput smul # set mode underline
		printf "$input_time"
		tput rmul # reset mode underline
		printf " "

		read -s -n 1 -t 1 reply

		[[ -n $reply ]] && break
		tput ed
		input_time=$(( $input_time - 1 ))

	done
	# '


	#: '
	read -s -n 1 -t 5 reply
	# '

}


reply_single() {

    # first entered character goes directly to $reply
    stty_0=$(stty -g)
	stty raw #-echo
    read -r reply
	# posix compliant version instead of zsh read:
	#reply=$(head -c 1)
    stty $stty_0

}


reply_single_hidden() {

    # string entry must be confirmed
	stty_0=$(stty -g)
	stty raw -echo
    reply=$(head -c 1)
	stty $stty_0

}
