#!/bin/bash

initial_screen() {

	clear
	printf "$script_name\n"
	printf "(c) $initial_release_year - $(date "+%Y") cytopyge\n"
	echo
	printf "This software is provided as is without warranty of any kind.\n"
	printf "Running this software is totally at your own risk.\n"
	echo
	echo

}
