#!/bin/bash
##
###
### sourcefile


# define reply functions

reply_plain() {

	# string entry must be confirmed explicitly (by pushing enter)
	read reply

}


reply_plain_hidden() {

	# string entry must be confirmed explicitly (by pushing enter)
        read -s reply

}


reply_single_hidden_timed() {

	read -s -n 1 -t 5 reply

}


reply_single() {

        # first entered character goes directly to $reply
        stty_0=$(stty -g)
	stty raw #-echo
        reply=$(head -c 1)
        stty $stty_0

}


reply_single_hidden() {

        # string entry must be confirmed
	stty_0=$(stty -g)
	stty raw -echo
        reply=$(head -c 1)
	stty $stty_0

}

