#! /usr/bin/env sh

###             _                     _
###   __ _  ___| |_     ___ _   _  __| | ___
###  / _` |/ _ \ __|   / __| | | |/ _` |/ _ \
### | (_| |  __/ |_    \__ \ |_| | (_| | (_) |
###  \__, |\___|\__|___|___/\__,_|\__,_|\___/
###  |___/        |_____|
###
###  # # # # # #
###       #
###  # # # # # #
###

: '
get_sudo
source function for priviledge elevation
copyright (c) 2019 - 2023  |  oxo

GNU GPLv3 GENERAL PUBLIC LICENSE
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
https://www.gnu.org/licenses/gpl-3.0.txt

@oxo@qoto.org


# dependencies
  sudo

# usage
  n/a

# examples
  n/a

# '


sourcing()
{
    source_dir="$XDG_DATA_HOME/c/git/code/source/function"

    ## when $source_dir does not exist
    if [ ! -d $source_dir ]; then

	user_name=$(logname)
	xdg_h="/home/$user_name"
	xdg_d_h="$xdg_h/.local/share"

	source_dir="$xdg_d_h/c/git/code/source/function"
    fi

    source "$source_dir/text_appearance"
}


get_sudo()
{
    printf "${fg_yellow}"

    sudo -v

    printf "${st_def}"
}


main()
{
    sourcing
    get_sudo
}

main
