#! /usr/bin/env sh
#
##
### # # # # # #
###      #
### # # # # # #
###
### source function
###
### (c) 2019 - 2023  |  oxo
##
#


sourching()
{
    source_dir="$XDG_DATA_HOME/c/git/code/source/function"

    ## when $source_dir does not exist
    if [ ! -d $source_dir ]; then

	user_name=$(logname)
	xdg_h="/home/$user_name"
	xdg_d_h="$xdg_h/.local/share"
	xdg_c_h="$xdg_h/.local/cache"

	source_dir="$xdg_d_h/c/git/code/source/function"
    fi

    source "$source_dir/text_appearance"
}


get_sudo()
{
    printf "${fg_yellow}"

    sudo -v

    printf "${st_def}"
}


main()
{
    sourching
    get_sudo
}

main
