#!/bin/bash
#
##
### source function
###
### 2019 - 2022  |  cytopyge
##
#


source_dir="$XDG_DATA_HOME/c/git/code/source/function"
source "$source_dir/text_appearance"


get_sudo()
{
    printf "${YELLOW}"

    sudo -v

    printf "${NOC}"
}

#get_sudo
