#! /usr/bin/env sh

#set -o errexit
#set -o nounset
#set -o pipefail

: '
----------------------------------------------------------------------
progress_bar
define a progress bar

copyright (c) 2021 - 2024  |  oxo

# # # # # #
     #
# # # # # #

GNU GPLv3 GENERAL PUBLIC LICENSE
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
https://www.gnu.org/licenses/gpl-3.0.txt

@oxo@qoto.org

dependencies:
none

usage:
bar $prog_perc $bar_width

with:
bar_width	(characters)
prog_perc (whole percentage)

todo:
print data inside bar
======================================================================
# '


bar() {
    elapsed=$(( $1*$2/100 ))

    # bar definition with spaces
    # printf -v assigns value to variable
    printf -v prog  "%${elapsed}s"
    printf -v total "%$(($2-elapsed))s"

    # %4s	reserves 4 chars for percentage
    # %s\r	print bar and carriage return
    printf '%4s%s\r' "[${prog// /#}${total}]   " "$prog_perc%"
}

#--------------------------------------------------------------------

bar_new()
{
    # usage: prog_bar 2 6 20 [0]
    step_curr="$1"
    step_total="$2"
    bar_cols="$3"
    no_info="$4"

    bar_border_left='['
    bar_prog_char='#'
    bar_info_text='abc'
    bar_border_right=']'

    ## maths
    step_rel=$((echo $1/$2*100) | bc -l)
}
