#! /usr/bin/env sh
#
##
### source function
##
#

# usage reply_functions $function [$max_time]


# NOTICE bash read -ne zsh read
# see note on read


args="$@"


# reply functions definitions


## posix compliant (w/o read)

reply_single()
{
    # first entered character goes directly to $reply
    stty_0=$(stty -g)
    stty raw echo icrnl

    reply=$(head -c 1)

    stty $stty_0
}


reply_single_hidden()
{
    # string entry must be confirmed
    stty_0=$(stty -g)
    stty raw echo icrnl

    reply=$(head -c 1)

    stty $stty_0
}


## with bash read function

reply_read_plain()
{
    # entry is visible
    # string entry must be confirmed explicitly (with eof (enter))
    read -r -e reply
}


reply_read_plain_hidden()
{
    # entry is not visible
    # string entry must be confirmed explicitly (with eof (enter))
    read -er -s reply
}


reply_read_single()
{
    # first entered character goes directly to $reply
    read -er -N 1 reply
}


reply_read_single_hidden()
{
    # first entered character goes directly to $reply
    read -er -N 1 -s reply
}


reply_read_single_hidden_timer()
{
    # timer visible
    # timer exits

    # possible error if host script is not #! /usr/bin/env sh
    # error while: set -e

    max_time="$1"
    [[ -n $max_time ]] && i="$max_time" || i=5

    tput sc

    ## while loop will be ran i times
    while [ $i -ge 0 ]; do

	tput rc
	tput rev	# set mode reverse video
	[ $i -ge 1 ] && printf "$i"
	#printf "$i"
	tput sgr0	# turn off all attributes
	printf " "

	reply_read_single_hidden_timed

	#[[ -n $reply ]] && break
	[[ -z $reply ]] || break
	tput ed

	i=$(( $i - 1 ))
	#i=$((i--))

    done
}


reply_read_single_hidden_timed()
{
    # timer not visible
    # timer exits
    # entry is not visible
    # first entered character goes directly to $reply
    local t=1

    ## use -t flag before -n flag to prevent '-t not an identifier' error
    ## (-N takes timer into account, see below)
    ## e flag causing info to disappear if timer bigger then 1
    ## -N returns after nchars, eof, or timer
    read -r -s -t $t -N 1 reply
}
