#! /usr/bin/env sh

args="$@"
getargs ()
{
    while [ "$#" -gt 0 ]; do
    # while :; do

	case "$1" in

	    a )
		a=1
		shift
		;;

	    '' )
		echo no_args
		;;

	    * ) return
		;;

	esac

    done
}
getargs $args
