#!/usr/bin/env sh
#
##
###                _       _
###  ___  ___ _ __(_)_ __ | |_     _ __   __ _ _ __ ___   ___
### / __|/ __| '__| | '_ \| __|   | '_ \ / _` | '_ ` _ \ / _ \
### \__ \ (__| |  | | |_) | |_    | | | | (_| | | | | | |  __/
### |___/\___|_|  |_| .__/ \__|___|_| |_|\__,_|_| |_| |_|\___|
###                 |_|      |_____|
###  _ _|_ _ ._    _  _
### (_\/|_(_)|_)\/(_|(/_
###   /      |  /  _|
###
### script_name
### one-line_description
### copyright (c) 2020 - 2022  |  cytopyge
###
### GNU GPLv3 GENERAL PUBLIC LICENSE
##### This file is part of Foobar.
#####
##### Foobar is free software: you can redistribute it and/or modify
#TODO OR
### This program is free software: you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program.  If not, see <https://www.gnu.org/licenses/>.
### https://www.gnu.org/licenses/gpl-3.0.txt
###
### y3l0b3b5z2u=:matrix.org @cytopyge@mastodon.social
###
##
#

## dependencies
#	$source_dir

## usage
#	cat header

## example
#	none


# initial definitions

## script
script_name='name'
developer='cytopyge'
license='gplv3'
initial_release='2020'

## hardcoded variables
#	none
source_dir="$XDG_DATA_HOME/c/git/code/source/function"

#--------------------------------



